app = "kimi-computer"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "/app/healthcheck.sh"

[env]
  OLLAMA_HOST = "http://ollama:11434"
  CHROMADB_HOST = "chromadb"
  CHROMADB_PORT = "8000"
  LOG_LEVEL = "INFO"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health"

[[services]]
  internal_port = 11434
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 11434

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 8000

[metrics]
  port = 9091
  path = "/metrics"

[vm]
  size = "shared-cpu-1x"
  memory = "512mb"

[experimental]
  allowed_public_ports = [80, 443, 8080, 11434, 8000]
  auto_rollback = true