#!/usr/bin/env python3
"""
AI-powered CMS content sync with proper output handling
"""

import os
import sys
import json

def generate_cms_content():
    """Generate CMS content using Moonshot AI"""
    api_key = os.getenv('MOONSHOT_API_KEY')

    if not api_key:
        print("❌ MOONSHOT_API_KEY not set", file=sys.stderr)
        sys.exit(1)

    # Your AI generation logic here
    # ...

    generated_content = {
        'sections': [
            {
                'title': 'Updated Hero Section',
                'content': '...',
                'timestamp': '2026-01-03'
            }
        ],
        'metadata': {
            'generated_by': 'moonshot-ai',
            'confidence': 0.95
        }
    }

    return generated_content

def write_to_github_output(key: str, value: str):
    """
    Write output that next workflow step can read
    CRITICAL FIX: This connects the "dead end" data flow
    """
    github_output = os.getenv('GITHUB_OUTPUT')

    if not github_output:
        print(f"{key}={value}")  # Fallback for local testing
        return

    # Multi-line output requires special handling
    delimiter = f"EOF_{key}"
    with open(github_output, 'a') as f:
        f.write(f"{key}<<{delimiter}\n")
        f.write(value)
        f.write(f"\n{delimiter}\n")

def main():
    print("🤖 Starting AI CMS Sync...")

    try:
        content = generate_cms_content()

        # Format PR body
        pr_body = f"""## 🤖 AI-Generated CMS Update

### Changes Summary
{json.dumps(content['sections'], indent=2)}

### Metadata
- **Generated By**: {content['metadata']['generated_by']}
- **Confidence**: {content['metadata']['confidence']}
- **Timestamp**: {content['metadata'].get('timestamp', 'N/A')}

### Review Checklist
- [ ] Content aligns with brand guidelines
- [ ] No sensitive information exposed
- [ ] Links and images are valid
- [ ] SEO metadata is appropriate
"""

        # CRITICAL: Write to GITHUB_OUTPUT so next step can use it
        write_to_github_output('body', pr_body)
        write_to_github_output('has_changes', 'true')

        print("✅ AI sync complete. Output written to GITHUB_OUTPUT")

    except Exception as e:
        print(f"❌ AI sync failed: {e}", file=sys.stderr)
        write_to_github_output('body', f"❌ AI generation failed: {str(e)}")
        write_to_github_output('has_changes', 'false')
        sys.exit(1)

if __name__ == '__main__':
    main()
