# CodeRabbit Configuration - Professional Grade
language: "en-US"

# Instructing the AI to act as a Senior Architect
tone_instructions: "As a Senior Technical Reviewer, provide professional, objective, and constructive feedback. Focus on logic errors, security vulnerabilities, performance bottlenecks, and architectural integrity. Avoid subjective style nitpicks. Be concise."

reviews:
  # 'chill' profile avoids excessive noise, relying on our specific instructions for depth
  profile: "chill"

  # Workflow settings
  request_changes_workflow: false
  review_status: true
  commit_status: true

  # Summary Configuration
  high_level_summary: true
  high_level_summary_instructions: "Provide a concise executive summary of the changes. Specifically highlight any modifications to: 1. Security mechanisms (Rate limits, Auth). 2. Database schemas. 3. External API integrations."
  high_level_summary_in_walkthrough: false

  # Auto-labeling (if supported in your plan, good for organization)
  suggested_labels: true
  auto_apply_labels: true
