 feature/anthropic-brain-integration-17755607396485422698
version: "2"
  high_level_summary: true
  auto_review:
    enabled: true
    ignore:
      - "dist/**"
      - "yarn.lock"
      - "package-lock.json"
checks:
  collaboration:
    # This check will flag pull requests that have a low docstring coverage.
    # The `threshold` is the minimum percentage of docstrings that must be present.
    # The `in_files` and `not_in_files` are glob patterns to include or exclude files.
    docstring_coverage:
      enabled: true
      threshold: 80
      in_files: ["**/*.py"]
      not_in_files: ["**/__init__.py", "**/test_*.py", "**/tests_*.py"]

  correctness:
    # This check will enforce a maximum length for pull request titles.
    # The `max_length` is the maximum number of characters allowed.
    title_max_length:
      enabled: true
      max_length: 80

  maintainability:
    # This check will look for TODOs and FIXMEs in the code.
    # The `message` is the comment that will be posted on the pull request.
    # The `in_files` and `not_in_files` are glob patterns to include or exclude files.
    todos_and_fixmes:
      enabled: true
      message: "Remove TODO/FIXME before merge - create a ticket instead"
      in_files: ["**/*.{js,ts,py,sh}"]

    # This check will look for console.log statements in the code.
    # The `message` is the comment that will be posted on the pull request.
    # The `in_files` and `not_in_files` are glob patterns to include or exclude files.
    no_console_log:
      enabled: true
      pattern: "console\\.(log|debug|info)"
      in_files: ["src/**/*.{js,ts}", "!**/*.test.{js,ts}"]
      message: "Remove console.log - use proper logging instead"


# CodeRabbit Configuration - Professional Grade
 fix/coderabbit-yaml-parsing-error-14153990587715603946
language: "en-US"

# Instructing the AI to act as a Senior Architect
tone_instructions: "You are a Senior Technical Reviewer. Provide professional, objective, and constructive feedback. Focus strictly on logic errors, security vulnerabilities (OWASP), performance bottlenecks, and architectural integrity. Avoid subjective style nitpicks unless they violate standard conventions (PEP8/ESLint). Be concise."

reviews:
  # 'chill' profile avoids excessive noise, relying on our specific instructions for depth
  profile: "chill"

  # Workflow settings
  request_changes_workflow: false
  review_status: true
  commit_status: true

  # Summary Configuration
  high_level_summary: true
  high_level_summary_instructions: "Provide a concise executive summary of the changes. Specifically highlight any modifications to: 1. Security mechanisms (Rate limits, Auth). 2. Database schemas. 3. External API integrations."
  high_level_summary_in_walkthrough: false

  # Auto-labeling (if supported in your plan, good for organization)
  auto_label:
    enabled: true
 feature/anthropic-brain-integration-17755607396485422698
    require_tests_for:
      - "error_handling_changes"
      - "validation_logic"
      - "security_critical_paths"

    missing_test_penalty: 30  # Minutes per untested critical path

# Code quality enforcement
quality_gates:
  # Block merge on critical issues
  blocking_severity: ["critical", "high"]

  # Require resolution
  require_resolution:
    - "command_injection"
    - "secret_leakage"
    - "data_loss_risk"
    - "http_status_lost"

  # Auto-fail conditions
  auto_fail:
    - pattern: "TODO|FIXME"
      in_files: ["**/*.{js,ts,py,sh}"]
      message: "Remove TODO/FIXME before merge - create proper tickets"

    - pattern: "console\.(log|debug|info)"
      in_files: ["src/**/*.{js,ts}", "!**/*.test.{js,ts}"]
      message: "Remove console.log - use proper logging framework"

    - pattern: "print\("
      in_files: ["**/*.py", "!**/test_*.py"]
      message: "Remove print() statements - use logging module"

# Enhanced documentation requirements
documentation:
  require_docstrings: true
  min_coverage: 80

  docstring_template: |
    """
    Brief one-line description.

    Detailed explanation of functionality, including:
    - Purpose and use cases
    - Input validation and constraints
    - Error conditions and handling
    - Side effects (DB writes, API calls, file I/O)

    Args:
        param_name (type): Description including validation rules

    Returns:
        type: Description of return value and possible values

    Raises:
        SpecificError: When and why this is raised

    Example:
        >>> function_call(params)
        expected_output

    Security:
        - List any security considerations
        - Document validation performed
        - Note any sensitive data handling
    """

  require_security_section: true  # For functions handling user input, auth, or data

# Comment quality
comments:
  require_actionable_feedback: true

  feedback_template: |
    ## Issue: {issue_name}

    **Severity**: {severity}
    **Impact**: {business_impact}
    **Attack Vector** (if security): {exploitation_scenario}

    **Current Code**:
    ```{language}
    {vulnerable_code}
    ```

    **Problems**:
    1. {specific_problem_1}
    2. {specific_problem_2}

    **Production-Ready Solution**:
    ```{language}
    {fixed_code_with_full_context}
    ```

    **Why This Fix Works**:
    - {technical_explanation_1}
    - {technical_explanation_2}

    **Testing Requirements**:
    - [ ] Unit test: {test_scenario_1}
    - [ ] Integration test: {test_scenario_2}
    - [ ] Security test: {test_scenario_3}

    **Estimated Fix Time**: {realistic_hours} hours

# Learning from past reviews
learning:
  enabled: true

  # Store these in .jules/learnings/
  remember:
    - "Shell scripts with $(find) need null-delimited processing"
    - "Exception handlers must not leak sensitive data"
    - "HTTP errors need status codes, not plain Error objects"
    - "File operations need backups and audit trails"
    - "Environment variables need format validation, not just presence checks"

  apply_learnings: true
  learning_confidence_threshold: 0.8

# Integration with development workflow
workflow:
  # Run additional checks
  pre_review_commands:
    - name: "shellcheck"
      command: "shellcheck **/*.sh"
      on_failure: "block"

    - name: "security_scan"
      command: "npm audit --audit-level=high"
      on_failure: "warn"

    - name: "type_check"
      command: "npm run type-check"
      on_failure: "block"

  # Post-review actions
  post_review_commands:
    - name: "update_metrics"
      command: "./scripts/log-review-metrics.sh"

    - name: "notify_security_team"
      condition: "has_security_issues"
      command: "slack-notify #security-alerts"

# Custom rules for this project
custom_rules:
  - name: "verify_system_shell_safety"
    files: ["verify_system.sh", "**/verify*.sh"]
    checks:
      - pattern: 'for .* in \$\('
        severity: "critical"
        message: "Use while-read loop with null delimiter"

      - pattern: 'grep.*\|'
        context: "not.*-print0"
        severity: "high"
        message: "Ensure grep input is null-delimited for safe parsing"

      - pattern: '\[\[.*=~.*\]\]'
        require: 'anchored_regex'
        message: "Regex patterns should be anchored (^...$) to prevent partial matches"

  - name: "python_error_handling"
    files: ["**/*.py"]
    checks:
      - require_specific_exceptions: true
        allowed_bare_catch: []  # Never allow bare except

      - require_logging: true
        in_exception_handlers: true

      - require_error_codes: true
        message: "Return structured errors with codes for client handling"

  - name: "typescript_http_errors"
    files: ["**/*.ts", "**/*.tsx"]
    checks:
      - pattern: 'throw new Error'
        context: 'express|fastify|next'
        severity: "high"
        message: "Use HttpError with status codes in HTTP handlers"

# Reporting
reporting:
  format: "detailed"

  include_in_report:
    - "security_analysis"
    - "effort_breakdown"
    - "test_coverage_gaps"
    - "technical_debt_introduced"
    - "remediation_priority"
    - "estimated_fix_time_per_issue"

  summary_template: |
    # Code Review Summary

    ## Risk Assessment
    - **Security Issues**: {security_count} ({critical_security_count} critical)
    - **Data Integrity Risks**: {data_integrity_count}
    - **Error Handling Gaps**: {error_handling_count}
    - **Missing Tests**: {untested_paths_count}

    ## Realistic Effort Estimate
    - **Critical Fixes**: {critical_hours} hours
    - **Major Fixes**: {major_hours} hours
    - **Minor Fixes**: {minor_hours} hours
    - **Testing**: {test_hours} hours
    - **Documentation**: {doc_hours} hours
    - **TOTAL**: {total_hours} hours

    ## Merge Decision
    {merge_decision_with_rationale}

    ## Top Priority Issues
    {top_3_issues_with_full_remediation}

    ## Required Actions Before Merge
    {checklist_of_blocking_items}

# Specific file patterns
path_instructions:
  "**/*.sh":
    require:
      - "shellcheck_pass"
      - "null_delimited_processing"
      - "no_word_splitting_vulnerabilities"

    reviewers_focus:
      - "Command injection vectors"
      - "File handling safety"
      - "Error propagation"
      - "Audit trail logging"

  "**/handlers/*.py":
    require:
      - "type_hints_complete"
      - "docstrings_present"
      - "specific_exception_handling"
      - "input_validation"
      - "no_secret_leakage"

    security_critical: true

  "**/*verify*.sh":
    require:
      - "comprehensive_validation"
      - "clear_error_messages"
      - "no_false_positives"
      - "safe_file_operations"

    testing_required: true

# Tone and communication
tone:
  style: "direct_and_actionable"

  avoid:
    - "Consider..." # Too weak
    - "You might want to..." # Too uncertain
    - "It would be nice if..." # Not actionable

  prefer:
    - "CRITICAL: {issue} enables {attack}"
    - "This code will fail when {scenario}"
    - "Fix required: {specific_solution}"
    - "Security risk: {specific_vulnerability}"

  include_proof_of_concept: true  # Show how to exploit issues
  include_test_cases: true        # Show how to test fixes
  include_full_solutions: true    # Show complete, production-ready code

 fix/coderabbit-yaml-parsing-error-14153990587715603946
