# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  auto_review:
    enabled: true
    ignore:
      - "dist/**"
      - "yarn.lock"
      - "package-lock.json"
  effort_estimation:
    enabled: true
    base_minutes: 15

language: "en-US"
