---
language: "en-US"
early_access: false
reviews:
  profile: "assertive"  # FIXED: Changed from 'professional' to 'assertive'
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
  path_instructions:
    - path: "**/*.ts"
      instructions: |
        Review TypeScript code for:
        - Type safety (no 'any' types without justification)
        - React best practices (hooks, component patterns)
        - Performance issues (unnecessary re-renders, memo usage)
        - Accessibility (ARIA labels, semantic HTML)

    - path: "**/*.py"
      instructions: |
        Review Python code for:
        - Type hints on all functions
        - Pydantic model validation
        - Security issues (SQL injection, XSS)
        - Performance (async/await usage, database queries)

    - path: "**/docker-compose*.yml"
      instructions: |
        Review Docker configurations for:
        - Security (no hardcoded secrets, non-root users)
        - Resource limits (memory, CPU)
        - Health checks on all services
        - Volume persistence for data

    - path: "monitoring/**"
      instructions: |
        Review monitoring configs for:
        - Correct datasource URLs and ports
        - Valid Prometheus query syntax
        - Grafana dashboard JSON structure
        - Alert threshold reasonableness

chat:
  auto_reply: true

