# CodeRabbit Configuration - Professional Grade (Fixed)
language: "en-US"

# Architecture-First Persona
tone_instructions: "You are a Senior Technical Reviewer. Provide professional, objective, and constructive feedback. Focus strictly on logic errors, security vulnerabilities (OWASP), performance bottlenecks, and architectural integrity. Avoid subjective style nitpicks unless they violate standard conventions (PEP8/ESLint). Be concise."

reviews:
  profile: "chill"
  request_changes_workflow: false
  review_status: true
  commit_status: true

  # Summary Configuration
  high_level_summary: true
  high_level_summary_instructions: "Provide a concise executive summary of the changes. Specifically highlight any modifications to: 1. Security mechanisms (Rate limits, Auth). 2. Database schemas. 3. External API integrations."

  # Automatic Review triggers
  auto_review:
    enabled: true
    drafts: false

  # Tools and Static Analysis
  tools:
    ast-grep:
      enabled: true
      rules:
        # FIXED: Using single quotes '' allows the backslash for regex
        - id: no-console-log
          pattern: 'console\.(log|debug|info)'
          message: "Remove console.log before merge - use the configured logger instead."
          languages: ["javascript", "typescript"]
          severity: info

    python-black:
      enabled: true

    ruff:
      enabled: true

chat:
  auto_reply: true
