# CodeRabbit Configuration - Professional Grade
language: "en-US"

# Instructing the AI to act as a Senior Architect
tone_instructions: "You are a Senior Technical Reviewer. Provide professional, objective, and constructive feedback. Focus strictly on logic errors, security vulnerabilities (OWASP), performance bottlenecks, and architectural integrity. Avoid subjective style nitpicks unless they violate standard conventions (PEP8/ESLint). Be concise."

reviews:
  # 'chill' profile avoids excessive noise, relying on our specific instructions for depth
  profile: "chill"

  # Workflow settings
  request_changes_workflow: false
  review_status: true
  commit_status: true

  # Summary Configuration
  high_level_summary: true
  high_level_summary_instructions: "Provide a concise executive summary of the changes. Specifically highlight any modifications to: 1. Security mechanisms (Rate limits, Auth). 2. Database schemas. 3. External API integrations."
  high_level_summary_in_walkthrough: false

  # Auto-labeling (if supported in your plan, good for organization)
  suggested_labels: true
  auto_apply_labels: true
