reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary: true
  auto_review:
    enabled: true
    ignore:
      - "dist/**"
      - "yarn.lock"
      - "package-lock.json"
  effort_estimation:
    enabled: true
    base_minutes: 15

checks:
  collaboration:
    docstring_coverage:
      enabled: true
      threshold: 80
      in_files:
        - "**/*.py"
      not_in_files:
        - "**/__init__.py"
        - "**/test_*.py"
        - "**/tests_*.py"

  correctness:
    title_max_length:
      enabled: true
      max_length: 80

  maintainability:
    todos_and_fixmes:
      enabled: true
      message: "Remove TODO/FIXME before merge - create a ticket instead"
      in_files:
        - "**/*.js"
        - "**/*.ts"
        - "**/*.py"
        - "**/*.sh"

    no_console_log:
      enabled: true
      pattern: "console\\.(log|debug|info)"
      in_files:
        - "src/**/*.js"
        - "src/**/*.ts"
      not_in_files:
        - "**/*.test.js"
        - "**/*.test.ts"
      message: "Remove console.log - use proper logging instead"

language: "en-US"
early_access: true
enable_free_tier: false

# Enhanced issue detection
issue_detection:
  security:
    enabled: true
    severity: "high"

  data_integrity:
    enabled: true

  error_handling:
    enabled: true

  testing:
    enabled: true

# Code quality enforcement
quality_gates:
  blocking_severity:
    - "critical"
    - "high"

# Documentation requirements
documentation:
  require_docstrings: true
  min_coverage: 80
  require_security_section: true

# Comment quality
comments:
  require_actionable_feedback: true

# Learning from past reviews
learning:
  enabled: true
  apply_learnings: true
  learning_confidence_threshold: 0.8

# Tone and communication
tone:
  style: "direct_and_actionable"
  include_proof_of_concept: true
  include_test_cases: true
  include_full_solutions: true

# Reporting
reporting:
  format: "detailed"
  include_security_analysis: true
  include_effort_breakdown: true
  include_test_coverage_gaps: true
