# .coderabbit.yaml — ARCHITECTURAL RECOVERY & UPGRADE
# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

reviews:
  auto_review:
    enabled: true
  # FIX: The only valid schemas are 'chill' or 'assertive'
  profile: assertive
  request_changes_workflow: true

  instructions:
    - paths: ["**/*.{py,json,yaml,yml}"]
      instruction: |
        Act as a Staff Site Reliability Engineer (SRE).
        **Primary Directive:** Enforce "Config-Code Synchronization" and "Clean Code Principles."

        1. **Config-Code Sync (The Ghost Variable Kill Switch):**
           - If a Python file uses `os.getenv("VAR_X")`, then `vercel.json` MUST list "VAR_X" in `env`.
           - If `vercel.json` lists "VAR_Y", it MUST be used in a Python file.
           - Flag any mismatch as **Critical Configuration Drift**.

        2. **Exception Architecture (TRY003 Enforcement):**
           - DO NOT allow raw strings in `raise` statements (e.g., `raise Exception("Error text")`).
           - REQUIRE custom exception classes in a dedicated `exceptions.py` module.
           - Example: `raise ConfigurationError("Missing ENV var")` where `ConfigurationError` is imported.

        3. **Legacy Purge:**
           - Any reference to "Airtable" is a Critical failure if the Jira ticket indicates migration.

        **Output Format (Strict Table):**
        | Severity | Type | Location | Analysis | #FIX-REQUIRED |
        | :--- | :--- | :--- | :--- | :--- |
