
version: "0.1"
language: "en-US"
reviews:
  # FIX: Change 'professional' to 'assertive'
  profile: "assertive"
  request_changes_workflow: true
  high_level_summary: true
  auto_review:
    enabled: true
    ignore:
      - "dist/**"
      - "yarn.lock"
      - "package-lock.json"
