name: 💰 The Automated Authority Engine (CData Resilient)

on:
  workflow_dispatch:
    inputs:
      keyword:
        description: 'The target keyword for the content campaign (e.g., "AI-driven marketing automation")'
        required: true

jobs:
  # 1. CONTENT GENERATION & FALLBACK (Handled by Vercel Router)
  # This job calls the Vercel app, which executes the CData/GLM-4 fallback logic.
  #------------------------------------------------------------------------------------
  generate_content:
    runs-on: ubuntu-latest
    outputs:
      blog_content: ${{ steps.call_router.outputs.blog_content }}
      source_model: ${{ steps.call_router.outputs.source_model }}
      keyword: ${{ github.event.inputs.keyword }}

    steps:
      - name: 1.1 - Call Vercel Intelligent Router for Content
        id: call_router
        run: |
          # The Vercel app's API endpoint handles:
          # 1. Research via Perplexity Pro.
          # 2. Primary generation via Mistral/Qwen (via CData).
          # 3. Fallback generation via GLM-4.
          # 4. Returns the final content and the model used.
          
          # NOTE: This assumes you have deployed your Vercel app and set up a public API endpoint.
          response=$(curl -s -X POST "${{ secrets.VERCEL_ROUTER_URL }}/api/generate" \
            -H "Content-Type: application/json" \
            -d '{
              "keyword": "${{ github.event.inputs.keyword }}"
            }')
            
          # Extract outputs from the Vercel response
          blog_content=$(echo "$response" | jq -r .blog_content)
          source_model=$(echo "$response" | jq -r .source_model)
          
          # Set outputs for the next job
          echo "blog_content=$blog_content" >> $GITHUB_OUTPUT
          echo "source_model=$source_model" >> $GITHUB_OUTPUT

# DISABLED: The distribute_and_track job is disabled due to missing CDATA_CONNECT_API secret.
# This job can be re-enabled once the secret is configured.
#
#  # 2. DISTRIBUTION & TRACKING (Handled by CData Connect)
#  # This job uses the CData Connect API to perform all distribution and tracking actions.
#  #------------------------------------------------------------------------------------
#  distribute_and_track:
#    needs: generate_content
#    runs-on: ubuntu-latest
#    env:
#      CDATA_API_ENDPOINT: ${{ secrets.CDATA_CONNECT_API }}
#      CDATA_API_KEY: ${{ secrets.CDATA_API_KEY }}
#      BLOG_TITLE: "The Ultimate Guide to ${{ needs.generate_content.outputs.keyword }}"
#      BLOG_CONTENT: ${{ needs.generate_content.outputs.blog_content }}
#      SOURCE_MODEL: ${{ needs.generate_content.outputs.source_model }}
#      KEYWORD: ${{ needs.generate_content.outputs.keyword }}
#      
#    steps:
#      - name: 2.1 - Publish Blog to WordPress via CData
#        run: |
#          curl -s -X POST "$CDATA_API_ENDPOINT" \
#            -H "Authorization: Bearer $CDATA_API_KEY" \
#            -H "Content-Type: application/json" \
#            -d '{
#              "query": "INSERT INTO WordPress (Title, Content, Status) VALUES ('"$BLOG_TITLE"', '"$BLOG_CONTENT"', 'publish')"
#            }'
#
#      - name: 2.2 - Schedule Social Media Blitz via CData (Social Pilot/Ayrshare)
#        run: |
#          # Assuming the Vercel router also generated a short social copy
#          SOCIAL_COPY="🚀 New post on $BLOG_TITLE! Generated by $SOURCE_MODEL. Read the full guide on $KEYWORD."
#          
#          curl -s -X POST "$CDATA_API_ENDPOINT" \
#            -H "Authorization: Bearer $CDATA_API_KEY" \
#            -H "Content-Type: application/json" \
#            -d '{
#              "query": "INSERT INTO SocialPilot (Message, Accounts, ScheduleTime) VALUES ('"$SOCIAL_COPY"', 'twitter,linkedin', 'NOW()+10m')"
#            }'
#
#      - name: 2.3 - Create Asana Task via CData
#        run: |
#          ASANA_TASK_NAME="Review Performance for Campaign: $KEYWORD"
#          ASANA_NOTES="Content generated by $SOURCE_MODEL. Check SEO and traffic in 7 days."
#          
#          curl -s -X POST "$CDATA_API_ENDPOINT" \
#            -H "Authorization: Bearer $CDATA_API_KEY" \
#            -H "Content-Type: application/json" \
#            -d '{
#              "query": "INSERT INTO Asana (WorkspaceId, ProjectId, Name, Notes) VALUES ('${{ secrets.ASANA_WORKSPACE_ID }}', '${{ secrets.ASANA_PROJECT_ID }}', '"$ASANA_TASK_NAME"', '"$ASANA_NOTES"')"
#            }'
#
#      - name: 2.4 - Log Campaign in Airtable via CData
#        run: |
#          curl -s -X POST "$CDATA_API_ENDPOINT" \
#            -H "Authorization: Bearer $CDATA_API_KEY" \
#            -H "Content-Type: application/json" \
#            -d '{
#              "query": "INSERT INTO Airtable (Keyword, Status, SourceModel) VALUES ('"$KEYWORD"', 'Published', '"$SOURCE_MODEL"')"
#            }'
#
#      - name: 2.5 - Log Event in Datadog via CData
#        run: |
#          DATADOG_TITLE="Authority Campaign Launch: $KEYWORD"
#          
#          curl -s -X POST "$CDATA_API_ENDPOINT" \
#            -H "Authorization: Bearer $CDATA_API_KEY" \
#            -H "Content-Type: application/json" \
#            -d '{
#              "query": "INSERT INTO Datadog (Title, Text, Tags) VALUES ('"$DATADOG_TITLE"', 'Content generated by $SOURCE_MODEL', 'source:github-actions, campaign:authority')"
#            }'

  # 3. MULTIMEDIA PRODUCTION (Agentic Task)
  # This is the complex, multi-step task delegated to the Manus Agent.
  #------------------------------------------------------------------------------------
  multimedia_production:
    needs: generate_content
    runs-on: ubuntu-latest
    steps:
      - name: 3.1 - Delegate Video Production to Manus Agent
        run: |
          # The Manus Agent will use the localAI models (Whisper, TTS, Image Gen) on your Alibaba instance
          # to produce the video, upload it, and update the Airtable record when complete.
          
          MANUS_PROMPT="Create a 60-second vertical video for YouTube Shorts and TikTok. Use the main blog content as the source for the script. Generate visuals using the localAI Stable Diffusion model on the Alibaba instance. Synthesize a voiceover using the localAI TTS model. Upload the final video to the connected YouTube and TikTok Studio accounts. Title: '60 Second Guide to ${{ needs.generate_content.outputs.keyword }}'."
          
          curl -X POST "https://api.manus.ai/v1/tasks" \
            -H "Authorization: Bearer ${{ secrets.MANUS_API_KEY }}" \
            -d '{
              "task_description": "'"$MANUS_PROMPT"'"
            }'

      - name: 3.2 - Notify Team via Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: "✅ Campaign LIVE for *${{ needs.generate_content.outputs.keyword }}*. Content generated by *${{ needs.generate_content.outputs.source_model }}*. Video production delegated to Manus Agent."
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```
