version: '3.8'

# This file is intended to be used alongside the main docker-compose.yml
# Example: docker-compose -f docker-compose.yml -f docker-compose.cost-optimizer.yml up

networks:
  # The main docker-compose file creates these networks.
  # We declare them as external to connect to them.
  monitoring:
    external: true
  backend:
    external: true

services:
  cost-optimizer:
    build:
      context: .
      dockerfile: Dockerfile.cost-optimizer
    container_name: labverse_cost_optimizer
    restart: unless-stopped
    ports:
      - "8083:8083"
    networks:
      # Connect to monitoring for Prometheus scraping
      - monitoring
      # Connect to backend for potential future use
      - backend
    healthcheck:
      test: "curl --fail http://localhost:8083/metrics || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s