version: '3.8'

# Lab-Verse AI Orchestration - Integrated with Core System
# This file extends the existing Lab-Verse infrastructure

services:
  # AI Orchestration Service (integrates with existing ecosystem)
  lab-verse-ai-orchestrator:
    image: n8nio/n8n:latest
    container_name: lab-verse-ai-orchestrator
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      # Core Lab-Verse Integration
      - LAB_VERSE_ENV=${LAB_VERSE_ENV:-production}
      - LAB_VERSE_SERVICE_NAME=ai-orchestrator
      
      # n8n Configuration (aligned with Lab-Verse patterns)
      - N8N_HOST=${LAB_VERSE_DOMAIN:-localhost}
      - N8N_PORT=5678
      - N8N_PROTOCOL=${LAB_VERSE_PROTOCOL:-https}
      - NODE_ENV=${LAB_VERSE_ENV:-production}
      - WEBHOOK_URL=${LAB_VERSE_BASE_URL}/api/v1/ai/webhook/
      - GENERIC_TIMEZONE=${LAB_VERSE_TIMEZONE:-UTC}
      - N8N_LOG_LEVEL=${LAB_VERSE_LOG_LEVEL:-info}
      
      # AI Provider Configuration
      - LAB_VERSE_AI_LOCAL_PREFERENCE=${USE_LOCAL:-true}
      - LAB_VERSE_AI_LOCALAI_URL=http://lab-verse-local-ai:8080
      - LAB_VERSE_AI_OPENROUTER_KEY=${OPENROUTER_API_KEY}
      - LAB_VERSE_AI_HUGGINGFACE_KEY=${HUGGINGFACE_API_KEY}
      
      # Database Integration (use existing Lab-Verse DB)
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${LAB_VERSE_DB_HOST:-lab-verse-postgres}
      - DB_POSTGRESDB_PORT=${LAB_VERSE_DB_PORT:-5432}
      - DB_POSTGRESDB_DATABASE=${LAB_VERSE_DB_NAME:-lab_verse}
      - DB_POSTGRESDB_USER=${LAB_VERSE_DB_USER}
      - DB_POSTGRESDB_PASSWORD=${LAB_VERSE_DB_PASSWORD}
    volumes:
      - lab_verse_ai_data:/home/node/.n8n
      - ./n8n/workflows:/home/node/.n8n/workflows
      - ./n8n/credentials:/home/node/.n8n/credentials
    depends_on:
      - lab-verse-local-ai
    networks:
      - lab-verse-network
    labels:
      - "lab-verse.service=ai-orchestrator"
      - "lab-verse.component=ai"

  # LocalAI Service (integrated with Lab-Verse monitoring and storage)
  lab-verse-local-ai:
    image: localai/localai:latest
    container_name: lab-verse-local-ai
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - LAB_VERSE_SERVICE_NAME=local-ai
      - LAB_VERSE_COMPONENT=ai-inference
      - MODELS_PATH=/models
      - CONTEXT_SIZE=4096
      - THREADS=${LAB_VERSE_AI_THREADS:-4}
      - GPU_LAYERS=${LAB_VERSE_AI_GPU_LAYERS:-0}
    volumes:
      - ${LAB_VERSE_AI_MODELS_PATH:-./localai/models}:/models
      - ./localai/config:/config
    networks:
      - lab-verse-network
    labels:
      - "lab-verse.service=local-ai"
      - "lab-verse.component=ai"

  # Vector Database Service
  lab-verse-vector-db:
    image: qdrant/qdrant:latest
    container_name: lab-verse-vector-db
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      - LAB_VERSE_SERVICE_NAME=vector-db
      - LAB_VERSE_COMPONENT=storage
    volumes:
      - lab_verse_vector_data:/qdrant/storage
    networks:
      - lab-verse-network
    labels:
      - "lab-verse.service=vector-db"
      - "lab-verse.component=storage"

volumes:
  lab_verse_ai_data:
    driver: local
  lab_verse_vector_data:
    driver: local

networks:
  lab-verse-network:
    name: ${LAB_VERSE_NETWORK_NAME:-lab-verse-network}
    external: ${LAB_VERSE_NETWORK_EXTERNAL:-false}
    driver: bridge