# prometheus.yml – Labverse Production Prometheus configuration
# -----------------------------------------------------------
# This file drives the “revenue monitoring” stack:
#   • Prometheus scrapes metrics from the app, Grafana, Alertmanager, …
#   • Alerts are sent to the Alertmanager service defined in docker‑compose
#   • Business‑specific rule files live under prometheus/rules/
#   • Optional exporters (Postgres, Redis, RabbitMQ, Blackbox) are
#     stubbed out for easy enable‑on‑demand.
# -----------------------------------------------------------

global:
  scrape_interval: 30s          # Default scrape interval for all jobs
  evaluation_interval: 30s      # How often rule files are evaluated
  external_labels:
    monitor: 'labverse-production'
    environment: 'production'
    region: 'africa'

# -----------------------------------------------------------------
# Where Prometheus sends alerts
# -----------------------------------------------------------------
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']   # Service name on the `monitoring` network

# -----------------------------------------------------------------
# Rule files – place your .yml files under prometheus/rules/
# -----------------------------------------------------------------
rule_files:
  - "rules/*.yml"

# -----------------------------------------------------------------
# Scrape configurations
# -----------------------------------------------------------------
scrape_configs:

  # -------------------------------------------------------------
  # 1️⃣  Labverse application – expose /metrics (e.g. FastAPI, Go, etc.)
  # -------------------------------------------------------------
  - job_name: 'labverse-app'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['web:8000']   # <-- ‘web’ is the service name of your API
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__metrics_path__]
        target_label: __metrics_path__

  # -------------------------------------------------------------
  # 2️⃣  Grafana – Prometheus‑compatible metrics endpoint
  # -------------------------------------------------------------
  - job_name: 'grafana'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance

  # -------------------------------------------------------------
  # 3️⃣  Prometheus self‑monitoring
  # -------------------------------------------------------------
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # -------------------------------------------------------------
  # 4️⃣  Alertmanager self‑monitoring
  # -------------------------------------------------------------
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  # -------------------------------------------------------------
  # 5️⃣  Node Exporter – host OS metrics
  # -------------------------------------------------------------
  # Node exporter runs on the host network (host‑mode), so we reach it via
  # the host's DNS name. Adjust the address if you prefer a static IP.
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:9100']
    scrape_interval: 60s   # Lower frequency to save bandwidth on African links

  # -------------------------------------------------------------
  # 6️⃣  Blackbox Exporter – HTTP/HTTPS endpoint probing
  # -------------------------------------------------------------
  # OPTIONAL: Add a blackbox‑exporter container (see Docker‑Compose) if you
  # want to monitor publicly‑exposed URLs (e.g. checkout page, payment API).
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]           # Use the http_2xx module (built‑in)
    static_configs:
      - targets:
          - https://api.yourdomain.com/healthz   # your app health endpoint
          - https://www.yourdomain.com            # public landing page
          - https://payments.yourdomain.com/api   # payment gateway health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115   # blackbox‑exporter service name

  # -------------------------------------------------------------
  # 7️⃣  PostgreSQL Exporter (optional – add container if needed)
  # -------------------------------------------------------------
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

  # -------------------------------------------------------------
  # 8️⃣  Redis Exporter (optional – add container if needed)
  # -------------------------------------------------------------
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']

  # -------------------------------------------------------------
  # 9️⃣  RabbitMQ Exporter (optional – add container if needed)
  # -------------------------------------------------------------
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq_exporter:9419']

  # -------------------------------------------------------------
  #  🔟  Additional custom business‑level metrics
  # -------------------------------------------------------------
  # Example: if your app publishes a custom “revenue_per_minute” metric,
  # you can create a dedicated job that scrapes it at a higher rate.
  # Uncomment & edit the block below when you add that endpoint.
  #
  # - job_name: 'revenue'
  #   metrics_path: '/metrics'
  #   scrape_interval: 10s
  #   static_configs:
  #     - targets: ['web:8000']
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: instance