global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'cardinality-guardian'
    static_configs:
      - targets: ['cardinality-guardian:8080']

  - job_name: 'cost-optimizer'
    static_configs:
      - targets: ['cost-optimizer:8083']
    metrics_path: '/metrics'
    scrape_interval: 30s