global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'labverse-alerts@localhost'
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
  routes:
  - match:
      severity: critical
    receiver: 'critical'
    
receivers:
- name: 'default'
  webhook_configs:
  - url: 'http://kimi-project-manager:8084/api/v1/alerts'
    send_resolved: true
    
- name: 'critical'
  webhook_configs:
  - url: 'http://kimi-project-manager:8084/api/v1/alerts/critical'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']