groups:
  - name: revenue.rules
    rules:
      # Alert if the average revenue per minute over the last 5 min falls below $500.
      - alert: LowRevenueRate
        expr: avg_over_time(app_revenue_per_minute[5m]) < 500
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Revenue rate dropped below $500/min"
          description: "Revenue per minute over the last 5 minutes is {{ $value }} which is below the acceptable threshold."

      # Alert on high error rate (5xx) that could hurt conversion.
      - alert: HighErrorRate
        expr: (sum(rate(http_requests_total{status=~"5.."}[2m]) / sum(rate(http_requests_total[2m]))) > 0.03
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "HTTP 5xx error rate > 3 %"
          description: "Error rate is {{ $value | humanizePercentage }} for the last 2 minutes."

      # Alert if checkout latency exceeds 2 seconds for more than 1 minute.
      - alert: CheckoutLatencyHigh
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{handler="/checkout"}[5m])) by (le) ) > 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "95‑th percentile checkout latency > 2 s"
          description: "Slow checkout could be hurting conversions – current 95‑pct latency is {{ $value }} s."