"""Real agent connector – talks to a local Ollama endpoint."""

from __future__ import annotations

import asyncio
import logging
from typing import Any, Dict, Iterable

import ollama
from fastapi import HTTPException, status

from server.telemetry import msg_sent_counter
from server.utils import resolve_local_model

log = logging.getLogger(__name__)

DEFAULT_MODEL = "llama2:7b"
MODEL_NAME = resolve_local_model(DEFAULT_MODEL)

log.info("Using Ollama model – %s", MODEL_NAME)


async def _generate_response(prompt: str) -> Dict[str, Any]:
    """
 codex/add-mypy-configuration-and-server-components
    Calls Ollama synchronously in a thread-pool and aggregates tokens.

    Returns a dict with the final content and the total token count.

    Generate a text response for the given prompt using the local Ollama model.
    
    Executes the Ollama call in a thread pool, collects streamed token fragments, and returns the concatenated response text together with a token count.
    
    Returns:
        dict: A dictionary with keys:
            - "content": The full concatenated response text (str).
            - "usage": A dict containing "total_tokens" (int) with the number of tokens collected.
    
    Raises:
        HTTPException: Raised with a 502 Bad Gateway status when the Ollama call fails; the exception detail contains the original error message.
 codex/implement-real-ollama-integration
    """
    loop = asyncio.get_running_loop()
    try:
        response = await loop.run_in_executor(
            None,
            lambda: ollama.generate(
                model=MODEL_NAME,
                prompt=prompt,
                stream=True,
                format="json",
            ),
        )
        if asyncio.iscoroutine(response):
            response = await response
    except Exception as exc:
        log.exception("Error from Ollama")
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=str(exc),
        ) from exc

    tokens = _extract_tokens(response)
    full_text = "".join(tokens)
    return {"content": full_text, "usage": {"total_tokens": len(tokens)}}


def _extract_tokens(response: Any) -> list[str]:
 codex/add-mypy-configuration-and-server-components

    """
    Normalize an Ollama response into a flat list of token strings.
    
    Accepts a single response that may be a dict (single chunk), None, or an iterable of chunk dicts, and returns the chunk "response" values as strings in order.
    
    Parameters:
        response (Any): An Ollama response which can be:
            - dict: a single chunk with a "response" key,
            - None: no content,
            - Iterable[dict]: a sequence of chunk dictionaries that may include None entries.
    
    Returns:
        list[str]: A list of token strings extracted from the "response" field of each chunk. For a dict input this yields a one-item list; for None it yields an empty list; for an iterable it preserves order and skips None chunks.
    """
 codex/implement-real-ollama-integration
    if isinstance(response, dict):
        return [str(response.get("response", ""))]
    if response is None:
        return []
    chunks: Iterable[Dict[str, Any]] = response
    return [str(chunk.get("response", "")) for chunk in chunks if chunk is not None]


async def stream_agent_response(query: str, session_id: str) -> Dict[str, Any]:
    """
 codex/add-mypy-configuration-and-server-components
    Public, async wrapper that streams an Ollama response back to the caller.

    Returns a dict that includes response text, latency in ms, and token count.

    Request a response from the local Ollama model and return the final text with timing and token usage.
    
    Parameters:
        query (str): Prompt text sent to the model.
        session_id (str): Identifier used for telemetry tagging of the request.
    
    Returns:
        Dict[str, Any]: A dictionary with:
            - "response" (str): The concatenated text generated by the model.
            - "latency_ms" (int): Elapsed time to generate the response in milliseconds.
            - "tokens" (int): Total number of tokens returned by the model.
 codex/implement-real-ollama-integration
    """
    loop = asyncio.get_running_loop()
    start = loop.time()
    result = await _generate_response(query)
    latency_ms = int((loop.time() - start) * 1000)

    msg_sent_counter.add(1, {"event": "agent_response", "session_id": session_id})

    return {
        "response": result["content"],
        "latency_ms": latency_ms,
        "tokens": result["usage"]["total_tokens"],
 codex/add-mypy-configuration-and-server-components
    }

    }
 codex/implement-real-ollama-integration
