openrouter:
  primary: anthropic/claude-sonnet-4       # Best quality
  fallbacks:
    - google/gemini-2.5-flash              # Fast + cheap
    - meta-llama/llama-4-scout:free        # Free tier
    - deepseek/deepseek-v3-base:free       # Backup free

direct_providers:  # When OpenRouter unavailable
  - dashscope (qwen)
  - moonshot
  - grok
  - glm-4

edge_local:
  - ollama:qwen2:7b
  - ollama:mixtral:8x7b