# Configuration for the Cost Optimizer Service
anomaly_detection:
  strategy: "zscore"
  threshold: 3.5

optimization:
  default_strategy: "spot_instances"

model_caching:
  enabled: true
  path: "/app/models"