import os
import json
import requests
import base64

# --- CONFIGURATION ---
# Read connection details from environment variables for security
WORDPRESS_URL = os.getenv("WORDPRESS_URL", "https://deedk822.wordpress.com")
WORDPRESS_USER = os.getenv("WORDPRESS_USER")
WORDPRESS_APP_PASSWORD = os.getenv("WORDPRESS_APP_PASSWORD")

def create_digital_product(product_data):
    """
    Creates a new digital product in Easy Digital Downloads via the WordPress REST API.

    Args:
        product_data (dict): A dictionary containing the product details.
    """
    if not WORDPRESS_USER or not WORDPRESS_APP_PASSWORD:
        print("[FATAL] Missing WORDPRESS_USER or WORDPRESS_APP_PASSWORD environment variables.")
        print("Please generate an Application Password in your WordPress admin dashboard.")
        return

    # The REST API endpoint for EDD products (which are a custom post type called 'download')
    api_url = f"{WORDPRESS_URL}/wp-json/wp/v2/downloads"

    # Encode credentials for Basic Authentication
    credentials = f"{WORDPRESS_USER}:{WORDPRESS_APP_PASSWORD}"
    token = base64.b64encode(credentials.encode()).decode('utf-8')
    headers = {
        'Authorization': f'Basic {token}',
        'Content-Type': 'application/json'
    }

    print(f"[INFO] Attempting to create new product: '{product_data.get('title')}'")

    try:
        response = requests.post(api_url, headers=headers, json=product_data)
        response.raise_for_status()  # Raise an exception for bad status codes (4xx or 5xx)

        new_product = response.json()
        print("[SUCCESS] New digital product created successfully!")
        print(f"  ID: {new_product.get('id')}")
        print(f"  Link: {new_product.get('link')}")
        print(f"  Price: {new_product.get('meta', {}).get('edd_price', 'Not set')}")

        return new_product

    except requests.exceptions.HTTPError as e:
        print(f"[FATAL] HTTP Error: {e.response.status_code} {e.response.reason}")
        print(f"  Response: {e.response.text}")
    except requests.exceptions.RequestException as e:
        print(f"[FATAL] A connection error occurred: {e}")
    except Exception as e:
        print(f"[FATAL] An unexpected error occurred: {e}")

def main():
    """
    Main execution function to demonstrate creating a product.
    """
    print("--- WordPress Monetization Engine: Product Creation Workflow ---")

    # This is a sample product generated by an AI Judge (e.g., The Operator)
    # In a real workflow, this data would be generated dynamically.
    sample_product = {
        "title": "AI-Generated Python Script: Automated Data Cleaner",
        "content": "A powerful Python script generated by The Operator AI. This tool automatically cleans and formats CSV files, saving you hours of manual work.",
        "status": "publish",  # Set to 'publish' to make it live, or 'draft'
        "meta": {
            "edd_price": "150.00",  # Price in your store's currency (e.g., ZAR)
            # In a real scenario, the script would first upload a file to the
            # WordPress media library and then link its ID here.
            # "edd_download_files": [{"attachment_id": "123", "name": "data_cleaner.py"}]
        }
    }

    create_digital_product(sample_product)

if __name__ == "__main__":
    main()
