#!/bin/bash
set -e

echo "🔧 JULES ENVIRONMENT SETUP: VAAL AI EMPIRE..."
echo "Performing pre-flight checks for required secrets..."

# Helper function for checking secrets
check_secret() {
  if [ -z "$1" ]; then
    echo "❌ CRITICAL ERROR: Secret '$2' is missing from the environment."
    echo "Please go to your repository's Settings > Secrets and variables > Actions to add it."
    exit 1
  fi
}

# --- 1. SAFETY CHECKS: VERIFY ALL SECRETS EXIST ---

# Brains & Core AI
check_secret "$DASHSCOPE_API_KEY" "DASHSCOPE_API_KEY"
check_secret "$MISTRALAI_API_KEY" "MISTRALAI_API_KEY"
check_secret "$COHERE_API_KEY" "COHERE_API_KEY"
check_secret "$HUGGINGFACE_API_KEY" "HUGGINGFACE_API_KEY"

# Alibaba Cloud Infrastructure
check_secret "$ACCESS_KEY_ID" "ACCESS_KEY_ID"
check_secret "$ACCESS_KEY_SECRET" "ACCESS_KEY_SECRET"

# Business Tools & Reporting
check_secret "$USER_LOGON_NAME" "USER_LOGON_NAME"
check_secret "$JIRA_LINK" "JIRA_LINK"
check_secret "$JIRA_PROJECT_KEY" "JIRA_PROJECT_KEY"
check_secret "$NOTION_API_KEY" "NOTION_API_KEY"

# Data Sources
check_secret "$KAGGLE_USERNAME" "KAGGLE_USERNAME"
check_secret "$KAGGLE_API_TOKEN" "KAGGLE_API_TOKEN"

# Destination Platforms
check_secret "$WORDPRESS_USER" "WORDPRESS_USER"
check_secret "$WORDPRESS_PASSWORD" "WORDPRESS_PASSWORD"
check_secret "$WORDPRESS_SITE_URL" "WORDPRESS_SITE_URL"
check_secret "$ARYSHARE_API_KEY" "ARYSHARE_API_KEY"
check_secret "$MAILCHIMP_API_KEY" "MAILCHIMP_API_KEY"
check_secret "$MAILCHIMP_SERVER_PREFIX" "MAILCHIMP_SERVER_PREFIX"
check_secret "$MAILCHIMP_LIST_ID" "MAILCHIMP_LIST_ID"
check_secret "$MANAGE_WIX_API_KEY" "MANAGE_WIX_API_KEY"
check_secret "$WIX_SITE_ID" "WIX_SITE_ID"
check_secret "$WIX_ACCOUNT_ID" "WIX_ACCOUNT_ID"

echo "✅ All required secrets are present."

# --- 2. THE BRIDGE: GENERATE DYNAMIC .ENV FILE ---

ENV_FILE="vaal-ai-empire/.env"
echo "Generating dynamic .env file at $ENV_FILE..."

# Clear existing file to ensure a clean state
> "$ENV_FILE"

# Write all secrets to the .env file for the Python app
{
  echo "# Auto-generated by Jules setup script"
  echo "DASHSCOPE_API_KEY=$DASHSCOPE_API_KEY"
  echo "MISTRAL_API_KEY=$MISTRALAI_API_KEY"
  echo "COHERE_API_KEY=$COHERE_API_KEY"
  echo "HUGGINGFACE_API_KEY=$HUGGINGFACE_API_KEY"

  echo "OSS_ACCESS_KEY_ID=$ACCESS_KEY_ID"
  echo "OSS_ACCESS_KEY_SECRET=$ACCESS_KEY_SECRET"
  echo "OSS_ENDPOINT=https://oss-eu-west-1.aliyuncs.com"
  echo "OSS_BUCKET=vaal-vault"

  echo "JIRA_USER_EMAIL=$USER_LOGON_NAME"
  echo "JIRA_API_TOKEN=$JIRA_LINK"
  echo "JIRA_URL=https://dimakatsomoleli.atlassian.net"
  echo "JIRA_PROJECT_KEY=$JIRA_PROJECT_KEY"

  echo "KAGGLE_USERNAME=$KAGGLE_USERNAME"
  echo "KAGGLE_KEY=$KAGGLE_API_TOKEN"

  echo "NOTION_API_KEY=$NOTION_API_KEY"

  echo "WORDPRESS_USERNAME=$WORDPRESS_USER"
  echo "WORDPRESS_APP_PASSWORD=$WORDPRESS_PASSWORD"
  echo "WORDPRESS_SITE_URL=$WORDPRESS_SITE_URL"

  echo "AYRSHARE_API_KEY=$ARYSHARE_API_KEY"

  echo "MAILCHIMP_API_KEY=$MAILCHIMP_API_KEY"
  echo "MAILCHIMP_SERVER_PREFIX=$MAILCHIMP_SERVER_PREFIX"
  echo "MAILCHIMP_LIST_ID=$MAILCHIMP_LIST_ID"

  echo "WIX_API_KEY=$MANAGE_WIX_API_KEY"
  echo "WIX_SITE_ID=$WIX_SITE_ID"
  echo "WIX_ACCOUNT_ID=$WIX_ACCOUNT_ID"
} >> "$ENV_FILE"

echo "✅ .env file generated successfully."

# --- 3. STANDARD INSTALL & VERIFICATION ---
echo "📦 Installing Python dependencies..."
pip install --upgrade pip
pip install -r vaal-ai-empire/requirements.txt
pip install -e vaal-ai-empire/

echo "🧠 Verifying Neural Link..."
python3 -c "from vaal_ai_empire.src.core.empire_supervisor import EmpireSupervisor; print('✅ Supervisor Loaded Successfully')"

echo "🚀 JULES SETUP COMPLETE. READY FOR EXECUTION."
